# The path of a folder containing students' submissions.
# It can be relative path to project root, or absolute path.
base_dir: assignment_html/
# Name of this grading work.
name: Assignment 1
# Set the rules of assessment.
rubric:
  - q_id: '1'  # question_id, unique for each question.
    caption: Overall Structure  # A short caption, describing what this question is about.
    assessment:  # Describe how to assess answers, as a list of (score, definition) pairs.
      - score: 2
        definition:   # Use single quote mark if the definition has multiple lines.
          'The article contains Title, Authors, Abstract, Introduction, Related Work, Methodology, Experiments 
          and Results, Conclusion, and References. All parts are well balanced.'
      - score: 1
        definition: Some parts are missing, or the balance is off.
      - score: 0
        definition: The essential structural parts are missing.
  - q_id: '2'
    caption: Problem statement
    assessment:
      - score: 4
        definition:
          'The topic is introduced, and the groundwork is laid as to the direction of the article. A research 
          question/hypothesis or goal has been identified.'
      - score: 2
        definition: Readers are aware of the overall problem, challenge, or topic that is to be examined.
      - score: 0
        definition: No reference is made to the topic that is to be examined.
